### ISSUE TITLE
add software to the sdk to support twoliter

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-sdk#108]
### Description

Add the following things to the `bottlerocket-sdk`:

- [x] `cargo make`
- [x] ~~`cargo deny`~~
- [x] `docker` (the CLI only, not the daemon)
- [x] Bottlerocket's RPM macros
- [x] Bootconfig data files

### Definition of Done

When the above items have been added to the SDK.

#### Depends on:

- [x] https://github.com/bottlerocket-os/twoliter/issues/6

```
id: texec_sdk
epic: twoliter_exec
```

Related to https://github.com/bottlerocket-os/bottlerocket/issues/2669

**Comment by webern** [comment]
It's unusual for us to require something to be released before the GitHub issue is done. So I changed the definition of done and added https://github.com/bottlerocket-os/bottlerocket/issues/3187

**Comment by bcressey** [comment]
We already have `cargo-deny` in the SDK, so I crossed that off.

**Comment by bcressey** [comment]
For the bootconfig data, we have two files:
* `empty-bootconfig.data` - addressed in https://github.com/bottlerocket-os/bottlerocket/pull/3189
* `qemu-x86-console-bootconfig.data` - used by `start-local-vm`

I'm not sure what the fate of the other content in `tools` will be long-term; maybe it all gets relocated to a "contrib" repo of some sort, or rewritten as `twoliter` helper commands (e.g. `twoliter-start-local-vm` can be a local helper script invoked by `twoliter start-local-vm ...`), which can embed the data file as a base64 string or whatever.

**Comment by webern** [comment]
> I'm not sure what the fate of the other content in `tools`

Most of the rest of the tools will go to the twoliter GitHub repository and be "embedded" in with the twoliter CLI. But you're right, I haven't thought about the "workflow" and "helper" type scripts. It's possible those conveniences could also be added to twoliter.

**Comment by bcressey** [comment]
Added these to the SDK.
