### ISSUE TITLE
Support multiple versions of Go

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket-sdk#177]
**Issue or Feature Request:**

 Support multiple versions of Go in the bottlerocket-sdk. This is necessary for releasing *k8s-1.30 variants of bottlerocket, as kubernetes requires a minimum version of Go 1.22 to build. There are ongoing `runc` issues with upgrading to Go 1.22 that are the motivation of this feature.

bottlerocket k8s-1.30 work is tracked in https://github.com/bottlerocket-os/bottlerocket/issues/3862

`update-go.sh` will have to be modified to support this.

**Comment by bcressey** [comment]
Done in #178.
