### ISSUE TITLE
Unable to disable `cross_check_fips` in RPM

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-sdk#190]
**Image I'm using:**
v0.42.0

**Issue or Feature Request:**
I'm building an RPM that I would like to avoid running the [check-fips script](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/6a9042cbefa86e8c7a99b6717190aa3c74dfdd1e/macros/check-fips). We [expose a macro `cross_check_fips`](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/6a9042cbefa86e8c7a99b6717190aa3c74dfdd1e/macros/shared#L269) which should be able to control it, but it seems that redefining the macro to `0` or using `%undefine` doesn't result in the desired behavior. It's possibly something to do with [this conditional](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/6a9042cbefa86e8c7a99b6717190aa3c74dfdd1e/macros/shared#L275).

I'm working around this issue for now with a macro like this:

```
%global __cross_check_fips_cmd true
```

**Comment by bcressey** [comment]
This ended up being an issue with duplicated macro definitions, which was fixed by https://github.com/bottlerocket-os/twoliter/pull/392.
