### ISSUE TITLE
Align sdk versioning with each bottlerocket-os version for easier coorelation between the two

### ISSUE THREAD

**Issue by faarshad** [bottlerocket-os/bottlerocket-sdk#35]
**Image I'm using:**
`bottlerocket/sdk-x86_64:v0.12.0`

**Issue or Feature Request:**
- The current versioning scheme of `bottlerocket-sdk` container images don't align with the versioning scheme of bottlerocket-os e.g. there is no way to say that `bottlerocket/sdk-x86_64:v0.12.0` was the base layer for building the  `bottlerocket-aws-k8s-1.16-x86_64-v1.0.1-2a181156` or `bottlerocket-aws-k8s-1.16-x86_64-v1.0.0-b0e2bc22` AMI
- An sdk versioning scheme that has maybe the bottlerocket-os version in it would be more amenable e.g. `bottlerocket/sdk-x86_64:v1.0.0-b0e2bc22`. It might be the case that for minor bottlerocket-os versions there is no change needed on the sdk-image but I did still tag those images with bottlerocket-os version in the interest of consistency over duplication.

cc: @bcressey @jhaynes

**Comment by tjkirch** [comment]
Hi @farshad-hobsons!  The development and release processes of Bottlerocket and the Bottlerocket SDK are separate, so we don't plan to use the same versioning information.  Today, if you want to tell which SDK version was used to build a Bottlerocket release, you can use a command like `git grep SDK v1.0.0:Makefile.toml`, for example, to check for Bottlerocket v1.0.0.  (Or the equivalent [GitHub URL](https://github.com/bottlerocket-os/bottlerocket/blob/v1.0.0/Makefile.toml).)  If this is a common need, we could consider making that mapping more obvious, but I'm not sure the versioning is the place to do it.
