### ISSUE TITLE
Update Rust to 1.53

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket-sdk#53]
https://blog.rust-lang.org/2021/05/06/Rust-1.52.0.html
https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html
https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html

**Comment by tjkirch** [comment]
Don't forget to update the GitHub Actions Rust version pinning at the same time: https://github.com/bottlerocket-os/bottlerocket/pull/1621/files

**Comment by jpculp** [comment]
Merged in and Actions were re-pinned to 1.53.
