### ISSUE TITLE
Document multi-arch build and publish steps

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-sdk#57]
The steps to build the SDK for both host architectures and both target architectures (four builds in all) are complicated. Additionally for use by Bottlerocket we also combine the host architectures into a multi-architecture tag/manifest.

The steps and scripts that we use to do this internally should be more-or-less identical to what anyone else would do if they wanted to build and publish the SDK to their own container image repos. Let's document these steps and include the helper script here.

**Comment by jpculp** [comment]
Opened PR for documentation. Will work on potential helper script in a later PR.
