### ISSUE TITLE
Update Rust to 1.56

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket-sdk#58]
https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html
https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html
https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html

**Comment by bcressey** [comment]
> Rustc will now search for custom JSON targets in /lib/rustlib/<target-triple>/target.json where / is the "sysroot" directory. You can find your sysroot directory by running rustc --print sysroot.

It'd be great if this lets us clean up the way we generate our custom Bottlerocket targets.
