### ISSUE TITLE
Move any licenses from `/usr/share/doc` to `/usr/share/licenses`

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-sdk#68]
**Issue or Feature Request:**
Some licenses are added to the wrong directory of the resulting SDK image (`/usr/share/doc` instead of `/usr/share/licenses`). This seems to be caused by certain packages not being updated to use [fedora's `%license` macro](https://fedoraproject.org/wiki/Changes/Use_license_macro_in_RPMs_for_packages_in_Cloud_Image) e.g. `maven-clean-plugin` [still uses `%doc`](https://src.fedoraproject.org/rpms/maven-clean-plugin/blob/rawhide/f/maven-clean-plugin.spec#_45).

We should correct this, possibly upstream if we can.

**Comment by stmcginnis** [comment]
This appears to be addressed now. There are just empty directories under `/usr/share/doc`:

```
[builder@d40a4594d235 ~]$ ls /usr/share/doc/
cmake  policycoreutils  python3-cryptography
[builder@d40a4594d235 ~]$ ls /usr/share/doc/cmake/
[builder@d40a4594d235 ~]$ ls /usr/share/doc/policycoreutils/
[builder@d40a4594d235 ~]$ ls /usr/share/doc/python3-cryptography/
docs
[builder@d40a4594d235 ~]$ ls /usr/share/doc/python3-cryptography/docs/
_static
[builder@d40a4594d235 ~]$ ls /usr/share/doc/python3-cryptography/docs/_static/
[builder@d40a4594d235 ~]$
```
